version: '2'

services:
    swagger-ui:
        container_name: swagger-ui
        image: swaggerapi/swagger-ui:3.18.2
        volumes:
            - .:/src/tmp
        ports:
            - 80:8080
        environment:
            - SWAGGER_JSON=/src/tmp/swagger.yaml
