AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for the DEVS coding 101 api
  
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs8.10
    Handler: app.handler

Parameters:
  twitterApiKey:
    Type: String
  twitterSecretKey:
    Type: String

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

  TweetsGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tweets-get/
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /tweets
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          TWITTER_API_KEY: !Sub ${twitterApiKey}
          TWITTER_SECRET_KEY: !Sub ${twitterSecretKey}

  SentimentPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sentiment-post
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /sentiment
            Method: POST
            RestApiId: !Ref Api
      Policies:
        - ComprehendBasicAccessPolicy: {}

